package com.mobilprog.tadam.mobilprog;


//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.8.1
//
// Created by Quasar Development at 22/04/2017
//
//---------------------------------------------------


import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class QMDBasicHttpBinding_ITyprXService {
    public List<HeaderProperty> httpHeaders;
    public boolean enableLogging;
    String url = "http://127.0.0.1:1334/Design_Time_Addresses/TyprX.Service/TyprXService/";
    int timeOut = 60000;

    public QMDBasicHttpBinding_ITyprXService() {
    }

    public QMDBasicHttpBinding_ITyprXService(String url) {
        this.url = url;
    }

    public QMDBasicHttpBinding_ITyprXService(String url, int timeOut) {
        this.url = url;
        this.timeOut = timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport() {
        try {
            java.net.URI uri = new java.net.URI(url);
            if (uri.getScheme().equalsIgnoreCase("https")) {
                int port = uri.getPort() > 0 ? uri.getPort() : 443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            } else {
                return new HttpTransportSE(url, timeOut);
            }

        } catch (java.net.URISyntaxException e) {
        }
        return null;
    }

    protected QMDExtendedSoapSerializationEnvelope createEnvelope() {
        QMDExtendedSoapSerializationEnvelope envelope = new QMDExtendedSoapSerializationEnvelope(QMDExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }

    protected java.util.List sendRequest(String methodName, QMDExtendedSoapSerializationEnvelope envelope, org.ksoap2.transport.Transport transport) throws java.lang.Exception {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj, java.lang.Object source, String resultName, QMDExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception {
        if (source == null) {
            return null;
        }
        if (source instanceof SoapPrimitive) {
            SoapPrimitive soap = (SoapPrimitive) source;
            if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        } else {
            SoapObject soap = (SoapObject) source;
            if (soap.hasProperty(resultName)) {
                java.lang.Object j = soap.getProperty(resultName);
                if (j == null) {
                    return null;
                }
                java.lang.Object instance = __envelope.get(j, destObj, false);
                return instance;
            } else if (soap.getName().equals(resultName)) {
                java.lang.Object instance = __envelope.get(source, destObj, false);
                return instance;
            }
        }

        return null;
    }

    public String Registration(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/Registration");
    }

    public String Login(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/Login");
    }

    public String PartnersList(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/PartnersList");
    }

    public String NewPartner(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/NewPartner");
    }

    public String AddPartnerToConversation(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/AddPartnerToConversation");
    }

    public String Message(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/Message");
    }

    public String GetMessages(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/GetMessages");
    }

    public String GetPasswordReminder(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/GetPasswordReminder");
    }

    public String UserSetting(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/UserSetting");
    }

    public String PasswordUpdate(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/PasswordUpdate");
    }

    public String LeaveConversation(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/LeaveConversation");
    }

    public String Logout(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/Logout");
    }

    public String NewConversation(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/NewConversation");
    }

    public String IgnoreUser(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/IgnoreUser");
    }

    public String RemoveUserIgnore(final String parameters) throws java.lang.Exception {
        return (String) execute(new QMDIWcfMethod() {
            @Override
            public QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() {
                QMDExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("", "parameters");
                __envelope.setOutputSoapObject(__soapReq);

                PropertyInfo __info = null;
                __soapReq.setInnerText(request);
                return __envelope;
            }

            @Override
            public java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object __result) throws java.lang.Exception {
                java.lang.Object j = __result;
                return j.toString();
            }
        }, "http://tempuri.org/ITyprXService/RemoveUserIgnore");
    }

    public String VerifyNewPartner(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String Ping(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String RemovePartner(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String RenameConversation(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String GetConversationHistory(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String GetHistory(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String SendFile(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String UploadProfilePict(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String GetUserProfile(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String AdminGetAllUser(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String BanUser(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String RemoveUserBan(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String PasswordReset(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    public String IsAdmin(final String parameters) throws java.lang.Exception {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;
    }

    protected java.lang.Object execute(QMDIWcfMethod wcfMethod, String methodName) throws java.lang.Exception {
        org.ksoap2.transport.Transport __httpTransport = createTransport();
        __httpTransport.debug = enableLogging;
        QMDExtendedSoapSerializationEnvelope __envelope = wcfMethod.CreateSoapEnvelope();
        try {
            sendRequest(methodName, __envelope, __httpTransport);

        } finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump", __httpTransport.requestDump);

                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump", __httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault) {
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault) __retObj;
            throw convertToException(__fault, __envelope);
        } else {
            return wcfMethod.ProcessResult(__envelope, __retObj);
        }
    }

    java.lang.Exception convertToException(org.ksoap2.SoapFault fault, QMDExtendedSoapSerializationEnvelope envelope) {

        return new java.lang.Exception(fault.faultstring);
    }


    interface QMDIWcfMethod {
        QMDExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(QMDExtendedSoapSerializationEnvelope __envelope, java.lang.Object result) throws java.lang.Exception;
    }
}


